define({
  "sourceSetting": "Pengaturan Sumber Pencarian",
  "instruction": "Tambah dan konfigurasikan layanan geocode atau layer fitur sebagai sumber pencarian. Sumber yang ditentukan ini menentukan apa yang dapat dicari dalam kotak pencarian.",
  "add": "Tambahkan Sumber Pencarian",
  "addGeocoder": "Tambahkan Geocoder",
  "geocoder": "Geocoder",
  "setLayerSource": "Tetapkan Sumber Layer",
  "setGeocoderURL": "Tetapkan URL Geocoder",
  "searchableLayer": "Feature Layer",
  "name": "Nama",
  "countryCode": "Kode Negara atau Wilayah",
  "countryCodeEg": "mis. ",
  "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
  "generalSetting": "Pengaturan Umum",
  "allPlaceholder": "Tempat placehoder untuk mencari semua: ",
  "showInfoWindowOnSelect": "Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",
  "searchInCurrentMapExtent": "Cari hanya dalam jangkauan peta saat ini",
  "zoomScale": "Skala Zoom",
  "locatorUrl": "URL Geocoder",
  "locatorName": "Nama Geocoder",
  "locatorExample": "Contoh",
  "locatorWarning": "Versi geocode service ini tidak didukung. Widget mendukung geocode service versi 10.0 dan lebih tinggi.",
  "locatorTips": "Saran tidak tersedia karena geocoding service tidak mendukung kapabilitas saran.",
  "layerSource": "Sumber Layer",
  "searchLayerTips": "Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",
  "placeholder": "Teks Placeholder",
  "searchFields": "Kolom Pencarian",
  "displayField": "Tampilkan Kolom",
  "exactMatch": "Persis",
  "maxSuggestions": "Saran Maksimal",
  "maxResults": "Hasil Maksimal",
  "setSearchFields": "Atur Kolom Pencarian",
  "set": "Atur",
  "fieldSearchable": "dapat dicari",
  "fieldName": "Nama",
  "fieldAlias": "Alias",
  "ok": "Ya",
  "cancel": "Batal",
  "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses."
});